# Generated by Django 6.0.1 on 2026-02-03 14:54

import Backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_rename_categories_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True, validators=[Backend.models.validated_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Other')], default='M', max_length=10),
        ),
    ]
