# Generated by Django 6.0.1 on 2026-02-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_user_dob_alter_user_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
