# Generated by Django 6.0.1 on 2026-02-06 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name_plural': 'Addresses'},
        ),
    ]
