# Generated by Django 6.0.1 on 2026-02-12 15:49

import Backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[Backend.models.validated_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Other')], default='M', max_length=10),
        ),
    ]
